@endpoint=http://localhost:{{$dotenv PORT}}/v1/api
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJkZW5pcyIsImNvaW5zIjowLCJpc192ZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzA5NTAyNzA1LCJleHAiOjE3MDk1Mzg3MDV9.u10ZyLpEaF9-VWjjhH9VysrUKD0dkFhmb07JNK2zNWA

### INSCRIPTION        
POST {{endpoint}}/user/signup 
Content-Type: application/json
 
{
	"username": "denis",
	"email": "denis.pianelli@gmail.com",
	"password": "qwertyui"
}
  
### CONNEXION
POST {{endpoint}}/user/signin
Content-Type: application/json

{
	"username": "denis",
	"password": "qwertyui"

} 

### RECUPERATION DE L'UTILISATEUR 
GET {{endpoint}}/user/
Authorization: {{token}}

### MISE A JOUR DES DONNEES UTILISATEUR  
PATCH {{endpoint}}/user/
Authorization: {{token}}
Content-Type: application/json

{
	"password": "qwertyui",
	"newPassword": "totototo",
	"newPasswordConfirm": "totoo"	
} 
 
### DEMANDE DE REINITILIATION DU MOT DE PASSE 
POST {{endpoint}}/account/reset/password
Content-Type: application/json

{
	"email": "denis.pianelli@gmail.com"

} 

### REINITILIATION DU MOT DE PASSE 
PATCH {{endpoint}}/account/reset/password
Content-Type: application/json
Authorization: {{token}}

{
	"newPassword": "qwertyui",
	"newPasswordConfirm": "qwertyui"

} 

### CHARACTER
GET {{endpoint}}/weapon

### GET ALL UNLOCKED CHARACTERS
GET {{endpoint}}/user/unlocked_character
Authorization: {{token}}  

### POST UNLOCKED CHARACTER
POST {{endpoint}}/user/unlocked_character
Authorization: {{token}}
Content-Type: application/json

{
	"userId": 1,
	"characterId": 3
} 